### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by EgorFront** [Calvin-LL/vue-responsive-images-example#29]
OS: Windows 10
Node: 10.16.3v

The project cannot be run on Windows.  It looks like the problem is with the paths in [webpack-image-srcset-loader](https://github.com/Calvin-LL/webpack-image-srcset-loader)

![image](https://user-images.githubusercontent.com/42942944/115727597-08962400-a384-11eb-901e-bb6f4c5890b4.png)

**Comment by Calvin-LL** [comment]
Thanks for letting me know, I'll take a look this weekend. The libraries weren't tested on windows at all but I suspect it's something to do with how Windows format path names.

**Comment by EgorFront** [comment]
Any changes?
Maybe you need more information about the problem? I tried to figure out what the problem is on my own, but I have no experience in developing wepack loaders

I really like this project, but I can't use it

Is there anything I can do to help?

**Comment by Calvin-LL** [comment]
Sorry about the delay, spent quite a bit of time last weekend trying to get a windows VM running. The fastest solution would be to use WSL since it works fine in Linux. I'll do some debugging today. I'll let you know what I find.

**Comment by Calvin-LL** [comment]
Just found out why, I'll update. Also check out https://github.com/Calvin-LL/vue-image-modernizer/tree/main/packages/vue-cli-plugin-image-modernizer if you find this project interesting.

**Comment by Calvin-LL** [comment]
Should work now. Thanks for alerting me to this issue.
